Repository cloudfoundry/bosh-linux-stemcell-builder, pull requests merged in 2019-08, with the labels that each got.

#76 add system_alicloud_modules
  bosh-stemcell/lib/bosh/stemcell/stage_collection.rb
  bosh-stemcell/spec/bosh/stemcell/stage_collection_spec.rb
  bosh-stemcell/spec/stemcells/azure_spec.rb
  stemcell_builder/stages/system_alicloud_modules/apply.sh
Labels: unscheduled

#88 Set SSH ClientAliveInterval to 900
  stemcell_builder/stages/base_ssh/apply.sh
  stemcell_builder/stages/system_azure_wala/assets/etc/waagent.conf
Labels: unscheduled

#96 blacklist nouveau kernel module
  stemcell_builder/stages/system_kernel_modules/apply.sh
Labels: in progress

#100 Add repack-helpers for customizing stemcells
  scripts/repack-helpers/README.md
  scripts/repack-helpers/example-repack-stemcell-with-custom-agent.sh
  scripts/repack-helpers/extract-image.sh
  scripts/repack-helpers/extract-stemcell.sh
  scripts/repack-helpers/mount-image.sh
  scripts/repack-helpers/pack-stemcell.sh
  scripts/repack-helpers/repack-stemcell.sh
  scripts/repack-helpers/run-in-chroot.sh
  scripts/repack-helpers/unmount-image.sh
  scripts/repack-helpers/update-file.sh
Labels: unscheduled

#95 Add CIS and STIG audit rules
  bosh-stemcell/spec/stemcells/cis_spec.rb
  bosh-stemcell/spec/stemcells/stig_spec.rb
  bosh-stemcell/spec/support/os_image_shared_examples.rb
  stemcell_builder/stages/bosh_audit/shared_functions.bash
Labels: scheduled
