Repository cloudfoundry/bosh-linux-stemcell-builder, pull requests merged in 2021-07, with the labels that each got.

#168 Delete obsolete rsyslog asset files
  bosh-stemcell/spec/stemcells/google_spec.rb
  bosh-stemcell/spec/support/os_image_shared_examples.rb
  bosh-stemcell/spec/support/stemcell_shared_examples.rb
  stemcell_builder/stages/rsyslog_config/apply.sh
  stemcell_builder/stages/rsyslog_config/assets/avoid-startup-deadlock.conf
  stemcell_builder/stages/rsyslog_config/assets/centos_init_d
  stemcell_builder/stages/rsyslog_config/assets/rsyslog_upstart.conf
Labels: bionic, unscheduled

#177 Fixes rsyslog configuration files issues
  bosh-stemcell/spec/stemcells/google_spec.rb
  bosh-stemcell/spec/support/stemcell_shared_examples.rb
  stemcell_builder/stages/rsyslog_config/apply.sh
Labels: bionic, unscheduled

#176 bump ruby to 2.7.3
  .rubocop.yml
  Gemfile
  Gemfile.lock
  bosh-stemcell/.rubocop.yml
  ci/docker/os-image-stemcell-builder-bionic/install-ruby.sh
  ci/docker/os-image-stemcell-builder-bionic/scripts/ubuntu_bashrc
  vendor/cache/diff-lcs-1.3.gem
  vendor/cache/diff-lcs-1.4.4.gem
  vendor/cache/fakefs-0.19.2.gem
  vendor/cache/fakefs-1.3.2.gem
  vendor/cache/logging-2.2.2.gem
  vendor/cache/logging-2.3.0.gem
  vendor/cache/multi_json-1.13.1.gem
  vendor/cache/multi_json-1.15.0.gem
  vendor/cache/rake-10.5.0.gem
  vendor/cache/rake-13.0.3.gem
  vendor/cache/rspec-3.10.0.gem
  vendor/cache/rspec-3.8.0.gem
  vendor/cache/rspec-core-3.10.1.gem
  vendor/cache/rspec-core-3.8.0.gem
  vendor/cache/rspec-expectations-3.10.1.gem
  vendor/cache/rspec-expectations-3.8.2.gem
  vendor/cache/rspec-its-1.2.0.gem
  vendor/cache/rspec-its-1.3.0.gem
  vendor/cache/rspec-mocks-3.10.2.gem
  vendor/cache/rspec-mocks-3.8.0.gem
  vendor/cache/rspec-support-3.10.2.gem
  vendor/cache/rspec-support-3.8.0.gem
  vendor/cache/timecop-0.9.1.gem
  vendor/cache/timecop-0.9.4.gem
Labels: bionic

#178 Fix infrastructure tests
  bosh-stemcell/spec/bosh/stemcell/infrastructure_spec.rb
Labels: bionic, unscheduled

#179 Remove asset files no longer needed for tests, this includes xenial and centos7 files.
  bosh-stemcell/spec/assets/dpkg-list-ubuntu-xenial-azure-additions.txt
  bosh-stemcell/spec/assets/dpkg-list-ubuntu-xenial-google-additions.txt
  bosh-stemcell/spec/assets/dpkg-list-ubuntu-xenial-softlayer-additions.txt
  bosh-stemcell/spec/assets/dpkg-list-ubuntu-xenial-vsphere-additions.txt
  bosh-stemcell/spec/assets/dpkg-list-ubuntu-xenial.txt
  bosh-stemcell/spec/assets/rpm-list-centos-7-azure-additions.txt
  bosh-stemcell/spec/assets/rpm-list-centos-7-google-additions.txt
  bosh-stemcell/spec/assets/rpm-list-centos-7-vsphere-additions.txt
Labels: bionic, unscheduled

#175 build stemcell for CloudStack with Xen
  bosh-stemcell/lib/bosh/stemcell/build_environment.rb
  bosh-stemcell/lib/bosh/stemcell/infrastructure.rb
  bosh-stemcell/lib/bosh/stemcell/stage_collection.rb
  bosh-stemcell/spec/assets/dpkg-list-ubuntu-bionic-cloudstack-additions.txt
  bosh-stemcell/spec/bosh/stemcell/infrastructure_spec.rb
  bosh-stemcell/spec/bosh/stemcell/stage_collection_spec.rb
  bosh-stemcell/spec/stemcells/cis_spec.rb
  bosh-stemcell/spec/stemcells/cloudstack_spec.rb
  bosh-stemcell/spec/stemcells/ubuntu_bionic_spec.rb
  bosh-stemcell/spec/support/stemcell_shared_examples.rb
  stemcell_builder/lib/helpers.sh
  stemcell_builder/stages/bosh_cloudstack_agent_settings/apply.sh
  stemcell_builder/stages/bosh_cloudstack_agent_settings/config.sh
  stemcell_builder/stages/bosh_cloudstack_ubuntu_vr_metadata/apply.sh
  stemcell_builder/stages/bosh_cloudstack_ubuntu_vr_metadata/assets/install.sh
  stemcell_builder/stages/bosh_cloudstack_ubuntu_vr_metadata/config.sh
  stemcell_builder/stages/image_install_grub/apply.sh
  stemcell_builder/stages/prepare_vhdx_image_stemcell/apply.sh
  stemcell_builder/stages/prepare_vhdx_image_stemcell/config.sh
  stemcell_builder/stages/system_ubuntu_xen_tools/apply.sh
  stemcell_builder/stages/system_vhd_utils_tools/apply.sh
Labels: unscheduled

#183 git cherry-pick 13a1c2bc1210affe4a0e1aaf4c6ee2ba1984009d: build stemcell for CloudStack with Xen
  bosh-stemcell/lib/bosh/stemcell/build_environment.rb
  bosh-stemcell/lib/bosh/stemcell/infrastructure.rb
  bosh-stemcell/lib/bosh/stemcell/stage_collection.rb
  bosh-stemcell/spec/assets/dpkg-list-ubuntu-bionic-cloudstack-additions.txt
  bosh-stemcell/spec/bosh/stemcell/infrastructure_spec.rb
  bosh-stemcell/spec/bosh/stemcell/stage_collection_spec.rb
  bosh-stemcell/spec/stemcells/cis_spec.rb
  bosh-stemcell/spec/stemcells/cloudstack_spec.rb
  bosh-stemcell/spec/stemcells/ubuntu_bionic_spec.rb
  bosh-stemcell/spec/support/stemcell_shared_examples.rb
  stemcell_builder/lib/helpers.sh
  stemcell_builder/stages/bosh_cloudstack_agent_settings/apply.sh
  stemcell_builder/stages/bosh_cloudstack_agent_settings/config.sh
  stemcell_builder/stages/bosh_cloudstack_ubuntu_vr_metadata/apply.sh
  stemcell_builder/stages/bosh_cloudstack_ubuntu_vr_metadata/assets/install.sh
  stemcell_builder/stages/bosh_cloudstack_ubuntu_vr_metadata/config.sh
  stemcell_builder/stages/image_install_grub/apply.sh
  stemcell_builder/stages/prepare_vhdx_image_stemcell/apply.sh
  stemcell_builder/stages/prepare_vhdx_image_stemcell/config.sh
  stemcell_builder/stages/system_ubuntu_xen_tools/apply.sh
  stemcell_builder/stages/system_vhd_utils_tools/apply.sh
Labels: unscheduled

#181 🐞 vCenter correctly displays IP address of VMs
  bosh-stemcell/spec/stemcells/ubuntu_bionic_spec.rb
  stemcell_builder/stages/system_open_vm_tools/apply.sh
Labels: unscheduled
